# Generated by Django 2.1.4 on 2018-12-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_id',
            field=models.TextField(null=True),
        ),
    ]
